version: '3.4'
services:
  rabbitmq:
    image: rabbitmq
    ports:  
      - - 5672:5672

  flower:  
    image: mher/flower
    command: flower --port=5555 --broker=amqp://RABBITMQ_DEFAULT_USER:RABBITMQ_DEFAULT_PASS@rabbitmq:5672
    ports:  
      - 5555:5555
    depends_on:
      - rabbitmq
   
  nginx:
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flower
