# Generated by Django 3.0.4 on 2020-03-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200314_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.RenameField(
            model_name='reconprotocol',
            old_name='recon_nf_file',
            new_name='nf_file',
        ),
        migrations.AlterField(
            model_name='study',
            name='recon_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recon_nf_file', to='app.ReconProtocol'),
        ),
    ]
